name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Ruff (lint)
        run: ruff check .

      - name: Markdown format (check only)
        run: mdformat --check .

      - name: Pytest
        run: pytest

  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link check (Markdown)
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --verbose
            --no-progress
            --max-concurrency 4
            --accept 200..299,403,429
            --exclude-path "CHANGELOG.md|LICENSE"
            -- *.md **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}